# Uncomment the next line to define a global platform for your project
#source 'https://github.com/CocoaPods/Specs'

inhibit_all_warnings!

platform :ios, '12.0'

target 'PubeasySDK' do
  
  # 使用相对路径（本地开发）
#   pod 'PubeasySDK', :path => '../'
  
  # 使用 GitHub 源（适用于所有电脑）
  pod 'PubyYanSDK', :podspec => 'https://raw.githubusercontent.com/guangyao/pbsdk/main/PubyYanSDK.podspec'
  
  # 使用 CocoaPods 官方源（需要等待 CDN 同步）
#   pod 'PubyYanSDK', '0.0.1'
  
end
