# Uncomment the next line to define a global platform for your project
#source 'https://github.com/CocoaPods/Specs'

inhibit_all_warnings!

platform :ios, '12.0'

target 'PubeasySDK' do
  
  # 使用相对路径
#   pod 'PubeasySDK', '0.3.8'
   pod 'PubeasySDK', :path => '../'
  
end
