# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'TestApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # 使用本地路径引用SDK
  pod 'PubyYanSDK', :path => '../'

end
